#!/bin/sh

# Copyright 2016 John Florian <jflorian@doubledog.org>
#
# This file is part of koji-helpers.
#
# koji-helpers is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version so long as this copyright notice remains intact.
#
# koji-helpers is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# koji-helpers.  If not, see <http://www.gnu.org/licenses/>.

# Logging levels:
EMERG=0
ALERT=1
CRIT=2
ERR=3
WARNING=4
NOTICE=5
INFO=6
DEBUG=7


say() {
    # Output a message with a priority prefix recognized by systemd-cat.
    local level=$1; shift
    printf '<%s>%s\n' $level "$@"
}

crit() {
    # Convenience function for say() at the CRITICAL priority level.
    say $CRIT "$@"
}

err() {
    # Convenience function for say() at the ERROR priority level.
    say $ERR "$@"
}

info() {
    # Convenience function for say() at the INFORMATION priority level.
    say $INFO "$@"
}

fail() {
    # Issue a message at the ERROR priority level and quit, returning
    # a non-success exit code.
    err "$@"
    exit 1
}

config_lines() {
    # Return, via stdout, lines within the specified configuration file that
    # are not comments nor empty lines nor lines consisting of nothing more
    # than whitespace.  In other words, the actual active configuration
    # content.
    local config="$1"
    grep -Ev '^[[:space:]]*#|^[[:space:]]*$' $config
}
